feat(update-proton-ge): Added failure information for parsing release

diff --git a/.local/bin/update-proton-ge b/.local/bin/update-proton-ge
--- a/.local/bin/update-proton-ge
+++ b/.local/bin/update-proton-ge
@@ -6,6 +6,12 @@ script_name=$(basename $0)
 
 is_updated="false"
 
+fail() {
+  local message="$@"
+  echo -e "\n$message"
+  return 1
+}
+
 update_proton_ge() {
   steam_comp_dir="$HOME/.local/share/Steam/compatibilitytools.d"
   steam_config_file="$HOME/.local/share/Steam/config/config.vdf"
@@ -20,11 +26,11 @@ update_proton_ge() {
 
   echo -e "\nGetting latest version"
   latest_uri="https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest"
-  latest_release_json=$(curl -f "$latest_uri") || return 1
-  latest_version=$(echo "$latest_release_json" | jq -r ".tag_name") || return 1
-  latest_asset=$(echo "$latest_release_json" | jq -r ".assets.[] | select(.name == \"${latest_version}.tar.gz\")") || return 1
-  latest_digest=$(echo "$latest_asset" | jq -r ".digest") || return 1
-  latest_download_url=$(echo "$latest_asset" | jq -r ".browser_download_url") || return 1
+  latest_release_json=$(curl -f "$latest_uri") || fail "No release found" || return 1
+  latest_version=$(echo "$latest_release_json" | jq -r ".tag_name") || fail "No latest version found in release" || return 1
+  latest_asset=$(echo "$latest_release_json" | jq -r -e ".assets.[] | select(.name == \"${latest_version}.tar.gz\")") || fail "No assets found in release" || return 1
+  latest_digest=$(echo "$latest_asset" | jq -r ".digest") || fail "No digest found in release" || return 1
+  latest_download_url=$(echo "$latest_asset" | jq -r ".browser_download_url") || fail "No download url found in release" || return 1
 
   if [ ! -d "$steam_proton_ge_dir" ]; then
     mkdir $steam_proton_ge_dir
@@ -63,7 +69,7 @@ update_proton_ge() {
   # Update steam config to latest proton-ge version
   sed -i "s/\"GE-Proton.*\"/\"$latest_version\"/" $steam_config_file
   # Update digest to latest version
-  echo "$latest_digest" > $steam_proton_ge_digest_file
+  echo "$latest_digest" >$steam_proton_ge_digest_file
 
   rm $latest_tar_file
   is_updated="true"
